model:
  class_path: module.lightning.MLPClassifier
  init_args:
    hidden_dim: 512
    num_layers: 5
    batch_norm: true
    layer_norm: false
    output_dim: 1
    dropout: 0.5
    activation: relu

data:
  class_path: data.sharded_datamodule.LargeHDF5MLPDataModule
  init_args:
    gen_data_path: /global/cfs/cdirs/m3443/usr/pmtuan/CaloINN/results/20260416_144506_full_training_odd_good_order/sample_train_clf_epoch300.hdf5
    truth_data_path: /pscratch/sd/p/pmtuan/ddsim/single_pion_discrete_validation_coarse_hcal/trainset_flat_good_order.hdf5
    test_data_path: /pscratch/sd/p/pmtuan/ddsim/single_pion_discrete_coarse_hcal/trainset_flat_good_order.hdf5
    xml_path: /global/cfs/cdirs/m3443/usr/pmtuan/caloinn_lightning/binning_pion_odd_coarse_hcal.xml
    particle: pion
    val_fraction: 0.05
    batch_size: 8192
    min_energy: 9500
    split_seed: 42
    num_workers: 8
    prefetch_factor: 8
    pin_memory: true
    voxel_energy_cutoff: 1
    cache_mode: memmap
    cache_dir: /pscratch/sd/p/pmtuan/cache/odd_Emin9.5GeV_voxel_cutoff1MeV_log_transform
    cache_chunk_size: 100000
    log_transform: true

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.001
    betas: [0.9, 0.999]
    eps: 1e-8
    amsgrad: true

lr_scheduler:
  class_path: torch.optim.lr_scheduler.StepLR
  init_args:
    step_size: 10
    gamma: 0.95

trainer:
  stage_dir: /pscratch/sd/p/pmtuan/caloxtreme_clf/
  accelerator: auto
  devices: 1
  num_nodes: 1
  max_epochs: 1000
  logger:
    - class_path: training_utils.wandb.WandbLogger
      init_args:
        stage_dir: /pscratch/sd/p/pmtuan/caloxtreme_clf
        project: caloxtreme_mlp
        group: voxel_cutoff_1MeV_logtransform
  callbacks:
    - class_path: training_utils.callbacks.checkpoint.ModelCheckpointCallback
      init_args:
        stage_dir: /pscratch/sd/p/pmtuan/caloxtreme_clf
        monitor: val_loss
        mode: min
        save_top_k: -1
        save_last: true
        verbose: true
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
